### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by Hajir-pro**
# Hi
My name is **Hajir**
26 years old
Iraqi
I live in Belgium
I like **coffee**

### CODE REVIEW

**Comment by snicoll** [comment]
@Hajir-pro did you create this from the GitHub web interface? Please keep in mind the assignment is to write your bio using a text editor and submit the PR using `git` (either via VSCode, another UI tool or the command line).

Before asking for a review, please look at the "Files Changed" tab that shows this PR suggests to remove a number of unrelated files. If you're having trouble, please ask questions rather than requesting a review without additional context.

**Comment by Hajir-pro** [comment]
@snicoll I guess the error is that I went to a new pull request and then chose to compare across fork, but now I understood that I  create a student-bio by clicking on Hack your Future/class-15 and then choosing a student-bio.Is this true?

**Comment by snicoll** [comment]
This is the question I asked:

> did you create this from the GitHub web interface? Please keep in mind the assignment is to write your bio using a text editor and submit the PR using git (either via VSCode, another UI tool or the command line).

**Comment by Hajir-pro** [comment]
@snicoll  ja,I created it on the Github interface and then Knew I should have used a text editor or VSCode....

**Comment by snicoll** [comment]
OK cool Let's follow-up on #107 then.

**Pull request closed without merging**
