### PR TITLE
WalterAlvar: bio

### PR DESCRIPTION
**Pull request by WalterAlvar**
### My first PR!
I just add my Bio in Markdown, everything checked and able to merge. 🏄🏽 

name | about | title | labels
-- | -- | -- | --
student bio | A template PR for student bios | Walter Alvarado: bio | student-bio

Quality checks:

- [x] My markdown code is tidy and contains no mistakes
- [x] I have previewed my bio and it looks the way I like it

linked to #11

### CODE REVIEW

**Review by snicoll — CHANGES_REQUESTED** [review]
@WalterAlvar thanks for all the details. This looks good for the most part. The assignment was to write your bio in markdown and some part have HTML in it. I understand that you may want images to look a certain way in a certain place but let's stick with markdown for a start please.

Can you please review your bio to remove the HTML? Check the [Markdown basic syntax guide](https://www.markdownguide.org/basic-syntax/#images-1) for more details.

You can update this PR by adding another commit with the change on your `master` and pushing again to your fork. Let me know if you have any questions!

**Comment by WalterAlvar** [comment]
Thanks Stéphane, the file is already updated now

**Review by snicoll — APPROVED** [review]
Well done @WalterAlvar!

**Comment by WalterAlvar** [comment]
PR reviewed and accepted

**Comment by snicoll** [comment]
@WalterAlvar you still need to merge the PR. Usually the reviewer does it but this exercise is about giving you an opportunity to do it.

**Pull request merged**
